[[redirects]]
  from = "/coronavirus"
  to = "https://www.as-submit.tk"
  status = 301
  force = true
  
[[redirects]]
  from = "/Submit"
  to = "https://www.as-submit.tk"
  status = 301
  force = true
